// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOAv8l9-S-aBZegHB9wxMwE30UjgeH6Po',
    appId: '1:959701495164:web:5a9b3b5963036580df88f9',
    messagingSenderId: '959701495164',
    projectId: 'nibm-unidesk',
    authDomain: 'nibm-unidesk.firebaseapp.com',
    storageBucket: 'nibm-unidesk.firebasestorage.app',
    measurementId: 'G-T1S9Z8FT4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQCBYonhXD16UQgtrs9KrZC1bllbonag',
    appId: '1:959701495164:android:47d79ae798c44fcbdf88f9',
    messagingSenderId: '959701495164',
    projectId: 'nibm-unidesk',
    storageBucket: 'nibm-unidesk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq01zOsa7coQg_cGUdDVPiAtw7lPV7GhI',
    appId: '1:959701495164:ios:c5a73a3ae3d99219df88f9',
    messagingSenderId: '959701495164',
    projectId: 'nibm-unidesk',
    storageBucket: 'nibm-unidesk.firebasestorage.app',
    iosBundleId: 'com.nibm.unidesk.unideskClient',
  );
}
